Repository chamjimayo/backend, pull requests merged in 2023-07, with the labels that each got.

#4 First Commit
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/project/chamjimayo/ChamjimayoApplication.java
  src/main/java/com/project/chamjimayo/Repository/Entity/BaseEntity.java
  src/main/java/com/project/chamjimayo/Repository/Entity/Board.java
  src/main/java/com/project/chamjimayo/Repository/Entity/BoardImage.java
  src/main/java/com/project/chamjimayo/Repository/Entity/Comment.java
  src/main/java/com/project/chamjimayo/Repository/Entity/Equipment.java
  src/main/java/com/project/chamjimayo/Repository/Entity/Restroom.java
  src/main/java/com/project/chamjimayo/Repository/Entity/RestroomManager.java
  src/main/java/com/project/chamjimayo/Repository/Entity/Review.java
  src/main/java/com/project/chamjimayo/Repository/Entity/User.java
  src/main/java/com/project/chamjimayo/Repository/repo.java
  src/main/resources/application.yml
  src/test/java/com/project/chamjimayo/ChamjimayoApplicationTests.java
Labels: FEAT🦾

#12 Mapping 수정
  src/main/java/com/project/chamjimayo/Repository/repo.java
  src/main/java/com/project/chamjimayo/domain/entity/BaseEntity.java
  src/main/java/com/project/chamjimayo/domain/entity/Board.java
  src/main/java/com/project/chamjimayo/domain/entity/BoardImage.java
  src/main/java/com/project/chamjimayo/domain/entity/Comment.java
  src/main/java/com/project/chamjimayo/domain/entity/Equipment.java
  src/main/java/com/project/chamjimayo/domain/entity/Restroom.java
  src/main/java/com/project/chamjimayo/domain/entity/RestroomManager.java
  src/main/java/com/project/chamjimayo/domain/entity/Review.java
  src/main/java/com/project/chamjimayo/domain/entity/Search.java
  src/main/java/com/project/chamjimayo/domain/entity/User.java
Labels: FIX🔨

#14 Feat: 공공데이터 DB에 저장 (#6)
  .gitignore
  build.gradle
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/domain/entity/Restroom.java
  src/main/java/com/project/chamjimayo/repository/RestroomRepository.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
  src/main/resources/application.yml
Labels: FEAT🦾, 심찬희⚽

#27 Fix #6 주변 화장실 찾기 응답 값 변경, 주변 화장실 요청 값 추가
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/controller/dto/NearByResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/RestroomDetailResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/RestroomNearByRequest.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
Labels: FEAT🦾, 심찬희⚽

#23 Fix: 화장실 검색 (#7), Feat: 리뷰 작성 (#9), Feat: 포인트 충전 (#10)
  src/main/java/com/project/chamjimayo/controller/GlobalExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/ReviewController.java
  src/main/java/com/project/chamjimayo/controller/ReviewExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/SearchController.java
  src/main/java/com/project/chamjimayo/controller/SearchExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/controller/UserExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/dto/ErrorStatus.java
  src/main/java/com/project/chamjimayo/controller/dto/PointChangeDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewRequestDto.java
  src/main/java/com/project/chamjimayo/controller/dto/SearchRequestDto.java
  src/main/java/com/project/chamjimayo/controller/dto/SearchResponseDto.java
  src/main/java/com/project/chamjimayo/domain/entity/Restroom.java
  src/main/java/com/project/chamjimayo/domain/entity/Review.java
  src/main/java/com/project/chamjimayo/domain/entity/Search.java
  src/main/java/com/project/chamjimayo/domain/entity/User.java
  src/main/java/com/project/chamjimayo/exception/PointLackException.java
  src/main/java/com/project/chamjimayo/exception/ReviewNotFoundException.java
  src/main/java/com/project/chamjimayo/repository/ReviewRepository.java
  src/main/java/com/project/chamjimayo/repository/SearchRepository.java
  src/main/java/com/project/chamjimayo/repository/UserJpaRepository.java
  src/main/java/com/project/chamjimayo/security/config/SecurityConfig.java
  src/main/java/com/project/chamjimayo/service/ReviewService.java
  src/main/java/com/project/chamjimayo/service/SearchService.java
  src/main/java/com/project/chamjimayo/service/UserService.java
Labels: FIX🔨, FEAT🦾, 조현태

#30 Fix: 화장실 검색 (#7), Fix: 리뷰 작성 (#9), Fix: 포인트 충전 (#10)
  src/main/java/com/project/chamjimayo/controller/ReviewController.java
  src/main/java/com/project/chamjimayo/controller/ReviewExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/SearchController.java
  src/main/java/com/project/chamjimayo/controller/SearchExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/controller/UserExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/dto/ErrorStatus.java
  src/main/java/com/project/chamjimayo/controller/dto/PointChangeDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewRequestDto.java
  src/main/java/com/project/chamjimayo/controller/dto/SearchResponseDto.java
  src/main/java/com/project/chamjimayo/domain/entity/Review.java
  src/main/java/com/project/chamjimayo/domain/entity/User.java
  src/main/java/com/project/chamjimayo/exception/JsonFileNotFoundException.java
  src/main/java/com/project/chamjimayo/service/ReviewService.java
  src/main/java/com/project/chamjimayo/service/SearchService.java
  src/main/java/com/project/chamjimayo/service/UserService.java
Labels: FIX🔨, 조현태

#31 Test: jwt 테스트 추가 (#5), Refactor: jwt 로직 리팩토링 (#5)
  build.gradle
  src/main/java/com/project/chamjimayo/security/JwtAuthenticationFilter.java
  src/main/java/com/project/chamjimayo/security/JwtTokenProvider.java
  src/main/java/com/project/chamjimayo/service/AuthService.java
  src/main/java/com/project/chamjimayo/service/AuthTokenService.java
  src/main/java/com/project/chamjimayo/service/UserService.java
  src/test/java/com/project/chamjimayo/security/JwtTokenProviderTest.java
  src/test/java/com/project/chamjimayo/service/AuthTokenServiceTest.java
Labels: TEST🚨, IMPROVE:art:

#32 Fix: 화장실 검색 (#7), Fix: 리뷰 작성 (#9), Fix: 포인트 충전 (#10)
  src/main/java/com/project/chamjimayo/controller/ReviewController.java
  src/main/java/com/project/chamjimayo/controller/ReviewExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/SearchController.java
  src/main/java/com/project/chamjimayo/controller/SearchExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/service/SearchService.java
Labels: FIX🔨, 조현태

#33 Fix: 화장실 검색 (#7), Fix: 리뷰 작성 (#9)
  src/main/java/com/project/chamjimayo/controller/ReviewController.java
  src/main/java/com/project/chamjimayo/controller/SearchController.java
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewRequestDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewResponseDto.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewUpdateDto.java
  src/main/java/com/project/chamjimayo/repository/ReviewRepository.java
  src/main/java/com/project/chamjimayo/repository/SearchRepository.java
  src/main/java/com/project/chamjimayo/security/config/SecurityConfig.java
  src/main/java/com/project/chamjimayo/service/ReviewService.java
  src/main/java/com/project/chamjimayo/service/SearchService.java
Labels: FIX🔨, FEAT🦾, 조현태
