Repository chamjimayo/backend, pull requests merged in 2023-08, with the labels that each got.

#39 Fix #8 "사용자 페이지"
  src/main/java/com/project/chamjimayo/controller/UserController.java
Labels: REFACTOR👉

#40 Fix: 화장실 검색 (#7)
  src/main/java/com/project/chamjimayo/service/SearchService.java
Labels: FIX🔨, 조현태

#42 Fix: 리뷰 작성 (#9)
  src/main/java/com/project/chamjimayo/controller/dto/RestroomDetailResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/ReviewResponseDto.java
Labels: FIX🔨, 조현태

#43 Fix#6 응답값 수정
  src/main/java/com/project/chamjimayo/controller/dto/NearByResponse.java
Labels: FIX🔨, 심찬희⚽

#48 Fix: "회원가입 & 로그인" (#8)
  src/main/java/com/project/chamjimayo/repository/TokenRepository.java
  src/main/java/com/project/chamjimayo/service/AuthService.java
  src/main/java/com/project/chamjimayo/service/AuthTokenService.java
Labels: IMPROVE:art:

#51 Feat#6 주변화장실 검색에 기능 추가
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/controller/RestroomExceptionHandler.java
  src/main/java/com/project/chamjimayo/controller/dto/ErrorStatus.java
  src/main/java/com/project/chamjimayo/controller/dto/PageDto.java
  src/main/java/com/project/chamjimayo/controller/dto/RestroomNearByRequest.java
  src/main/java/com/project/chamjimayo/exception/IndexException.java
  src/main/java/com/project/chamjimayo/exception/PageOutOfRangeException.java
  src/main/java/com/project/chamjimayo/repository/RestroomJpaRepository.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
Labels: FEAT🦾, 심찬희⚽

#52 Fix: 리뷰 작성 (#9)
  src/main/java/com/project/chamjimayo/controller/dto/ReviewResponseDto.java
  src/main/java/com/project/chamjimayo/service/ReviewService.java
Labels: FIX🔨, 조현태

#53 Fix: purchaseToken 검증 (#37)
  src/main/java/com/project/chamjimayo/controller/InAppPurchaseController.java
  src/main/java/com/project/chamjimayo/domain/entity/Product.java
  src/main/java/com/project/chamjimayo/domain/entity/User.java
  src/main/java/com/project/chamjimayo/service/InAppPurchaseService.java
  src/main/java/com/project/chamjimayo/service/ReceiptValidationService.java
  src/main/java/com/project/chamjimayo/service/RefundService.java
  src/main/java/com/project/chamjimayo/service/UserService.java
Labels: IMPROVE:art:

#58 Refactor: request, response, dto 분리(#55), Fix: 화장실 사용/종료 예외처리(#11)
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/controller/dto/request/EnrollRestroomRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/request/UsingRestroomRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/response/EndOfUsingRestroomResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/RestroomDetailResponse.java
  src/main/java/com/project/chamjimayo/controller/exception/handler/RestroomExceptionHandler.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
  src/main/java/com/project/chamjimayo/service/dto/EndOfUsingRestroomDto.java
  src/main/java/com/project/chamjimayo/service/dto/EnrollRestroomDto.java
  src/main/java/com/project/chamjimayo/service/dto/RestroomDetailDto.java
  src/main/java/com/project/chamjimayo/service/dto/RestroomNearByDto.java
  src/main/java/com/project/chamjimayo/service/dto/UsingRestroomDto.java
  src/main/java/com/project/chamjimayo/service/exception/ErrorStatus.java
  src/main/java/com/project/chamjimayo/service/exception/UsingRestroomException.java
Labels: FEAT🦾, REFACTOR👉, 심찬희⚽

#59 REFACTOR #55 request, response, dto 분리
  src/main/java/com/project/chamjimayo/controller/AuthController.java
  src/main/java/com/project/chamjimayo/controller/InAppPurchaseController.java
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/controller/dto/request/GoogleInAppPurchaseRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/response/AuthTokenResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/DuplicateCheckResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/RestroomSummaryResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/UserDetailsResponse.java
  src/main/java/com/project/chamjimayo/service/InAppPurchaseService.java
  src/main/java/com/project/chamjimayo/service/ReceiptValidationService.java
  src/main/java/com/project/chamjimayo/service/UserService.java
  src/main/java/com/project/chamjimayo/service/dto/AuthTokenDto.java
  src/main/java/com/project/chamjimayo/service/dto/DuplicateCheckDto.java
  src/main/java/com/project/chamjimayo/service/dto/GoogleInAppPurchaseDto.java
  src/main/java/com/project/chamjimayo/service/dto/PointDto.java
  src/main/java/com/project/chamjimayo/service/dto/RestroomSummaryDto.java
  src/main/java/com/project/chamjimayo/service/dto/UserDetailsDto.java
Labels: REFACTOR👉, 홍석호

#60 GlobalExceptionHandler 적용
  src/main/java/com/project/chamjimayo/controller/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/project/chamjimayo/service/exception/ApiKeyAuthenticationFilter.java
Labels: FIX🔨, 조현태

#61 FIX: purchaseToken 검증 수정 (#37)
  src/main/java/com/project/chamjimayo/repository/InAppOrderJpaRepository.java
  src/main/java/com/project/chamjimayo/repository/OrderJpaRepository.java
  src/main/java/com/project/chamjimayo/repository/OrderRepository.java
  src/main/java/com/project/chamjimayo/repository/domain/entity/InAppOrder.java
  src/main/java/com/project/chamjimayo/security/filter/ApiKeyAuthenticationFilter.java
  src/main/java/com/project/chamjimayo/service/OrderService.java
  src/main/java/com/project/chamjimayo/service/RefundService.java
Labels: IMPROVE:art:

#62 FIX: x-api-key 인증 필터 수정
  src/main/java/com/project/chamjimayo/security/config/SecurityConfig.java
  src/main/java/com/project/chamjimayo/security/exception/ApiKeyNotValidException.java
  src/main/java/com/project/chamjimayo/security/filter/ApiKeyAuthenticationFilter.java
  src/main/java/com/project/chamjimayo/security/filter/AuthenticationExceptionFilter.java
  src/main/java/com/project/chamjimayo/service/exception/ApiKeyAuthenticationFilter.java
  src/main/java/com/project/chamjimayo/service/exception/ErrorStatus.java
Labels: IMPROVE:art:

#64 FIX: 주변 화장실 반환값 수정 (#6)
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
Labels: FEAT🦾, 심찬희⚽

#65 Fix #11 화장실 포인트 관련 수정
  src/main/java/com/project/chamjimayo/controller/RestroomController.java
  src/main/java/com/project/chamjimayo/controller/dto/request/EnrollRestroomRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/response/NearByResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/RestroomDetailResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/UsingRestroomResponse.java
  src/main/java/com/project/chamjimayo/controller/exception/handler/RestroomExceptionHandler.java
  src/main/java/com/project/chamjimayo/repository/domain/entity/Restroom.java
  src/main/java/com/project/chamjimayo/service/RestroomService.java
  src/main/java/com/project/chamjimayo/service/dto/EndOfUsingRestroomDto.java
  src/main/java/com/project/chamjimayo/service/dto/EnrollRestroomDto.java
  src/main/java/com/project/chamjimayo/service/dto/UsingRestroomDto.java
Labels: FEAT🦾, 심찬희⚽

#66 FIX: 사용자 페이지 (#8)
  src/main/java/com/project/chamjimayo/controller/UserController.java
  src/main/java/com/project/chamjimayo/controller/dto/request/SignUpRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/request/UserAttributeChangeRequest.java
  src/main/java/com/project/chamjimayo/controller/dto/response/UserAttributeChangeResponse.java
  src/main/java/com/project/chamjimayo/controller/dto/response/UserDetailsResponse.java
  src/main/java/com/project/chamjimayo/controller/exception/handler/UserExceptionHandler.java
  src/main/java/com/project/chamjimayo/repository/UserQueryRepository.java
  src/main/java/com/project/chamjimayo/repository/domain/entity/User.java
  src/main/java/com/project/chamjimayo/service/UserService.java
  src/main/java/com/project/chamjimayo/service/dto/SignUpDto.java
  src/main/java/com/project/chamjimayo/service/dto/UserAttributeChangeDto.java
  src/main/java/com/project/chamjimayo/service/dto/UserDetailsDto.java
Labels: IMPROVE:art:

#67 Fix: 리뷰 작성 (#9)
  src/main/java/com/project/chamjimayo/controller/dto/response/ReviewResponse.java
  src/main/java/com/project/chamjimayo/service/ReviewService.java
Labels: FIX🔨, 조현태
